#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hitimes
Version  : 1.2.3
Release  : 6
URL      : https://rubygems.org/downloads/hitimes-1.2.3.gem
Source0  : https://rubygems.org/downloads/hitimes-1.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: rubygem-hitimes-lib
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
## hitimes
* [Homepage](http://github.com/copiousfreetime/hitimes)
* [Github project](http://github.com.org/copiousfreetime/hitimes)
* email jeremy at copiousfreetime dot org
* `git clone url git://github.com/copiousfreetime/hitimes.git`

%package lib
Summary: lib components for the rubygem-hitimes package.
Group: Libraries

%description lib
lib components for the rubygem-hitimes package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hitimes-1.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-hitimes.gemspec

%build
gem build rubygem-hitimes.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hitimes-1.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hitimes-1.2.2 && ruby -I.:lib:spec -e 'Dir.glob "./spec/*spec.rb", &method(:require)' && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/hitimes-1.2.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/cdesc-Interval.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/duration-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/duration_so_far-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/measure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/now-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/running%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/split-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/start_instant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/started%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/stop_instant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/stopped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/to_f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Interval/to_seconds-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/additional_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/cdesc-Metric.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/sampling_delta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/sampling_start_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/sampling_stop_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Metric/utc_microseconds-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/MutexedStats/cdesc-MutexedStats.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/MutexedStats/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/MutexedStats/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Paths/cdesc-Paths.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Paths/lib_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Paths/root_dir-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Paths/sub_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/cdesc-Stats.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/max-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/mean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/min-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/rate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/stddev-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/sum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/sumsq-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/Stats/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/cdesc-TimedMetric.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/measure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/now-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/running%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/split-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/stats-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedMetric/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/cdesc-TimedValueMetric.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/duration-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/measure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/now-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/rate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/running%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/split-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/timed_stats-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/unit_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/TimedValueMetric/value_stats-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/ValueMetric/cdesc-ValueMetric.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/ValueMetric/measure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/ValueMetric/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/ValueMetric/stats-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/ValueMetric/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/cdesc-Hitimes.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/Hitimes/measure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/RbConfig/cdesc-RbConfig.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/ext/hitimes/c/page-Makefile.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/ext/hitimes/java/src/hitimes/page-HitimesInterval_java.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/ext/hitimes/java/src/hitimes/page-HitimesService_java.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/ext/hitimes/java/src/hitimes/page-HitimesStats_java.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/ext/hitimes/java/src/hitimes/page-Hitimes_java.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/page-CONTRIBUTING_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/hitimes-1.2.3/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/hitimes-1.2.3/gem.build_complete
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/hitimes-1.2.3/gem_make.out
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/hitimes-1.2.3/mkmf.log
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/examples/benchmarks.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/examples/stats.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/.RUBYARCHDIR.-.hitimes.-.2.2.time
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes.c
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes.o
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_clock_gettime.c
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_clock_gettime.o
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_osx.c
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_osx.o
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_windows.c
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_instant_windows.o
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_interval.c
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_interval.h
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_interval.o
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_stats.c
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_stats.h
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes_stats.o
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/Hitimes.java
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/HitimesInterval.java
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/HitimesService.java
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/java/src/hitimes/HitimesStats.java
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/metric.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/mutexed_stats.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/paths.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/stats.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/timed_metric.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/timed_value_metric.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/value_metric.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/hitimes_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/interval_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/metric_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/mutex_stats_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/paths_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/stats_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/timed_metric_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/timed_value_metric_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/value_metric_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/spec/version_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/tasks/default.rake
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/tasks/extension.rake
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/tasks/this.rb
/usr/lib64/ruby/gems/2.2.0/specifications/hitimes-1.2.3.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/hitimes-1.2.3/hitimes/2.2/hitimes.so
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/ext/hitimes/c/hitimes.so
/usr/lib64/ruby/gems/2.2.0/gems/hitimes-1.2.3/lib/hitimes/2.2/hitimes.so
